name: Deploying on Demo Server

on:
  push:
    tags:
      - v*.*.*.*  #adding tag

jobs:
  build_and_test:
    runs-on: ubuntu-latest  #Github provided runner to run our image 

    steps:
      - name: Log the node version
        run: |
          node -v
          cat /etc/os-release
      - uses: actions/checkout@v2     #pulling code from repository
      - name: checkout
        run: mkdir -p /tmp/.build     #creating a .build folder
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'main') == false
        run: exit -1